alternatives: fix possible overrun
Error: STRING_NULL (CWE-170): [#def1] [important]
chkconfig-1.26/alternatives.c:591:13: string_null_source: Function "readlink" does not terminate string "buf". [Note: The source code implementation of the function has been overridden by a builtin model.]
chkconfig-1.26/alternatives.c:593:13: string_null: Passing unterminated string "buf" to "streq", which expects a null-terminated string.
  591|               readlink(l->facility, buf, sizeof(buf));
  592|
  593|->             if(!streq(sl, buf)) {
  594|                   unlink(l->facility);
  595|

Error: STRING_NULL (CWE-170): [#def2] [important]
chkconfig-1.26/alternatives.c:609:9: string_null_source: Function "readlink" does not terminate string "buf". [Note: The source code implementation of the function has been overridden by a builtin model.]
chkconfig-1.26/alternatives.c:611:9: string_null: Passing unterminated string "buf" to "streq", which expects a null-terminated string.
  609|           readlink(sl, buf, sizeof(buf));
  610|
  611|->         if(!streq(l->target, buf)) {
  612|               if (unlink(sl) && errno != ENOENT) {
  613|                   fprintf(stderr, _("failed to remove link %s: %s\n"), sl,