chkconfig: fix leak
Free the services field after we printed its contents.
Also remove the check for the return value of showServiceInfo,
since it is called with "forgiving" flag, so it can't return
an error.

Error: RESOURCE_LEAK (CWE-772):
chkconfig-1.26/chkconfig.c:524: alloc_arg: "readServices" allocates memory that is stored into "services".
chkconfig-1.26/chkconfig.c:528: noescape: Resource "services" is not freed or pointed-to in "qsort".
chkconfig-1.26/chkconfig.c:547: leaked_storage: Variable "services" going out of scope leaks the storage it points to.
  545|               fprintf(stderr, _("failed to open directory %s: %s\n"), XINETDDIR,
  546|                       strerror(err));
  547|->             return 1;
  548|           }
  549|           numServices = 0;